In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [12]:
weights = 2*np.random.random((2,1))-1
bias = 2*np.random.random(1)-1
weights, bias

(array([[-0.95246893],
        [-0.30769952]]),
 array([0.9316846]))

In [14]:
lr = 0.1
for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0,weights)+bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0,weights)+bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term*second_term

    changes = np.array([[0.0],[0.0]])

    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0]*output0[j][i]
    weights = weights- lr*changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0]*1
    bias = bias - lr*bias_change
ouptut = sig(np.dot(X,weights)+bias)
weights,bias, output

(array([[6.2671509],
        [6.2671509]]),
 array([-9.49055996]),
 array([[7.55624592e-05],
        [3.82952733e-02],
        [3.82952733e-02],
        [9.54510340e-01]]))

In [13]:
lr = 0.1
for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0,weights)+bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0,weights)+bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term*second_term

    changes = np.dot(output0.T,first_two)
    
    weights = weights- lr*changes
    bias_change = np.sum(first_two)
    bias = bias - lr*bias_change
ouptut = sig(np.dot(X,weights)+bias)
weights,bias, output

(array([[5.46627879],
        [5.4662788 ]]),
 array([-8.29216892]),
 array([[2.50452235e-04],
        [5.59441500e-02],
        [5.59441497e-02],
        [9.33412412e-01]]))

In [15]:
wh = 2-np.random.random((2,2))-1
wo = 2-np.random.random((2,1))-1
bh = 2-np.random.random((1,2))-1
bo = 2-np.random.random((1,1))-1
lr = 0.1


In [9]:
output0 = X
outputHidden = sig(np.dot(output0,wh)+bh)
output = sig(np.dot(outputHidden,wo)+bo)
output

array([[0.69435389],
       [0.70811458],
       [0.71525603],
       [0.72661853]])

### General Neural Network


In [16]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,1,1,0]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [17]:
wh = 2-np.random.random((2,2))-1
wo = 2-np.random.random((2,1))-1
bh = 2-np.random.random((1,2))-1
bo = 2-np.random.random((1,1))-1
lr = 0.1

In [19]:
for iter in range(10000):
    output0 = X
    inputHidden = np.dot(output0,wh)+bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden,wo)+bo
    output = sig(inputForOutputLayer)

    first_term_output_layer = output - Y
    second_term_ouptut_layer = derivativeSig(inputForOutputLayer)
    first_two_output_layer = first_term_output_layer*second_term_ouptut_layer

    first_term_hidden_layer = np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer*second_term_hidden_layer

    changes_output = np.dot(outputHidden.T,first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer,axis=0, keepdims=True)

    changes_hidden = np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer,axis=0, keepdims=True)

    wo = wo - lr*changes_output
    bo = bo - lr*changes_output_bias
    wh = wh - lr*changes_hidden
    bh = bh - lr*changes_hidden_bias

output0 = X
inputHidden = np.dot(output0,wh)+bh
outputHidden = sig(inputHidden)
inputForOutputLayer = np.dot(outputHidden,wo)+bo
output = sig(inputForOutputLayer)

output, wh, bh, wo, bo

(array([[0.06819006],
        [0.9359962 ],
        [0.93522368],
        [0.07071156]]),
 array([[5.66535816, 3.46140054],
        [5.88652146, 3.49997884]]),
 array([[-2.35261431, -5.31519171]]),
 array([[ 7.18163109],
        [-7.82031855]]),
 array([[-3.20035441]]))