In [13]:
from nltk.corpus import movie_reviews

In [14]:
movie_reviews.categories()

['neg', 'pos']

In [15]:
movie_reviews.fileids()

['neg/cv000_29416.txt',
 'neg/cv001_19502.txt',
 'neg/cv002_17424.txt',
 'neg/cv003_12683.txt',
 'neg/cv004_12641.txt',
 'neg/cv005_29357.txt',
 'neg/cv006_17022.txt',
 'neg/cv007_4992.txt',
 'neg/cv008_29326.txt',
 'neg/cv009_29417.txt',
 'neg/cv010_29063.txt',
 'neg/cv011_13044.txt',
 'neg/cv012_29411.txt',
 'neg/cv013_10494.txt',
 'neg/cv014_15600.txt',
 'neg/cv015_29356.txt',
 'neg/cv016_4348.txt',
 'neg/cv017_23487.txt',
 'neg/cv018_21672.txt',
 'neg/cv019_16117.txt',
 'neg/cv020_9234.txt',
 'neg/cv021_17313.txt',
 'neg/cv022_14227.txt',
 'neg/cv023_13847.txt',
 'neg/cv024_7033.txt',
 'neg/cv025_29825.txt',
 'neg/cv026_29229.txt',
 'neg/cv027_26270.txt',
 'neg/cv028_26964.txt',
 'neg/cv029_19943.txt',
 'neg/cv030_22893.txt',
 'neg/cv031_19540.txt',
 'neg/cv032_23718.txt',
 'neg/cv033_25680.txt',
 'neg/cv034_29446.txt',
 'neg/cv035_3343.txt',
 'neg/cv036_18385.txt',
 'neg/cv037_19798.txt',
 'neg/cv038_9781.txt',
 'neg/cv039_5963.txt',
 'neg/cv040_8829.txt',
 'neg/cv041_22364.txt',


In [16]:
movie_reviews.words(movie_reviews.fileids()[5])

['capsule', ':', 'in', '2176', 'on', 'the', 'planet', ...]

In [17]:
documents = []

for category in movie_reviews.categories():
    for fileid in movie_reviews.fileids(category):
        documents.append((movie_reviews.words(fileid),category))
documents[0:5]

[(['plot', ':', 'two', 'teen', 'couples', 'go', 'to', ...], 'neg'),
 (['the', 'happy', 'bastard', "'", 's', 'quick', 'movie', ...], 'neg'),
 (['it', 'is', 'movies', 'like', 'these', 'that', 'make', ...], 'neg'),
 (['"', 'quest', 'for', 'camelot', '"', 'is', 'warner', ...], 'neg'),
 (['synopsis', ':', 'a', 'mentally', 'unstable', 'man', ...], 'neg')]

In [18]:
import random
random.shuffle(documents)

In [19]:
documents[0:5]

[(['*', '*', '*', 'warning', '-', 'the', 'following', ...], 'neg'),
 (['it', "'", 's', 'time', 'to', 'take', 'cover', '.', ...], 'neg'),
 (['among', 'multitude', 'of', 'erotic', 'thrillers', ...], 'neg'),
 (['it', 'was', 'only', 'a', 'matter', 'of', 'time', ...], 'pos'),
 (['if', 'you', 'had', 'a', 'chance', 'to', 'create', ...], 'pos')]

In [23]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [21]:
from nltk.corpus import wordnet

In [25]:
from nltk.corpus import stopwords
import string
stops = set(stopwords.words('english'))
punctuations = list(string.punctuation)
stops.update(punctuations)
stops

{'!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'need

In [29]:
from nltk import pos_tag

In [37]:
def get_simple_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [27]:
def clean_words(words):
    output_words = []
    for w in words:
        if w.lower() not in stops:
            pos = pos_tag([w])
            clean_word = lemmatizer.lemmatize(w,pos=get_simple_pos(pos[0][1]))
            output_words.append(clean_word.lower())
    return output_words 

In [38]:
documents = [(clean_words(document),category)for document,category in documents]

In [39]:
documents[0]

(['warn',
  'follow',
  'review',
  'contains',
  'spoiler',
  'cast',
  'gary',
  'sinise',
  'cheadle',
  'connie',
  'nielsen',
  'jerry',
  'connell',
  'kim',
  'delaney',
  'tim',
  'robbins',
  'elise',
  'neal',
  'jill',
  'teed',
  'jody',
  'thompson',
  'bill',
  'timoney',
  'write',
  'jim',
  'thomas',
  'john',
  'thomas',
  'graham',
  'yost',
  'direct',
  'brian',
  'depalma',
  'run',
  'time',
  '115',
  'minute',
  'first',
  'big',
  'event',
  'movie',
  '2000',
  'turn',
  'anything',
  'gary',
  'sinise',
  'star',
  'astronaut',
  'remove',
  'mar',
  'mission',
  'astronaut',
  'wife',
  'maggie',
  'kim',
  'delaney',
  'becomes',
  'ill',
  'pass',
  'away',
  'cheadle',
  'give',
  'mission',
  'along',
  'russian',
  'couple',
  'young',
  'hotshot',
  'strange',
  'whirlwind',
  'shot',
  'top',
  'mar',
  'mountain',
  'range',
  'attack',
  'crew',
  'mission',
  'sinise',
  'robbins',
  'convince',
  'superior',
  'let',
  'neilsen',
  'connell',
  '

In [40]:
training_documents = documents[0:1500]
testing_documents = documents[1500:]

In [41]:
all_words = []
for doc in training_documents:
    all_words += doc[0]


In [43]:
import nltk

In [50]:
freq = nltk.FreqDist(all_words)
common = freq.most_common(3000)
features = [i[0] for i in common]

In [51]:
features

['film',
 'movie',
 'one',
 'make',
 'like',
 'character',
 'get',
 'see',
 'time',
 'go',
 'well',
 'scene',
 'even',
 'good',
 'story',
 'take',
 'would',
 'much',
 'also',
 'bad',
 'come',
 'give',
 'way',
 'two',
 'look',
 'life',
 'first',
 'know',
 'seem',
 '--',
 'end',
 'work',
 'thing',
 'play',
 'year',
 'plot',
 'say',
 'really',
 'show',
 'people',
 'little',
 'man',
 'could',
 'love',
 'star',
 'never',
 'try',
 'director',
 'new',
 'performance',
 'action',
 'great',
 'best',
 'u',
 'actor',
 'many',
 'big',
 'watch',
 'want',
 'think',
 'find',
 'role',
 'act',
 'back',
 'another',
 'world',
 'audience',
 'still',
 'something',
 'day',
 'turn',
 'old',
 'set',
 'guy',
 'however',
 'every',
 'real',
 'comedy',
 'though',
 'use',
 'feel',
 'cast',
 'point',
 'begin',
 'around',
 'enough',
 'interest',
 'part',
 'woman',
 'write',
 'last',
 'run',
 'long',
 'name',
 'may',
 'minute',
 'funny',
 'fact',
 'actually',
 'john',
 'young',
 'lot',
 'played',
 'script',
 'right',


In [52]:
def get_feature_dict(words):
    current_features= {}
    words_set = set(words)
    for w in features:
        current_features[w] = w in words_set
    return current_features

In [54]:
training_data = [(get_feature_dict(doc),category) for doc,category in training_documents]
testing_data = [(get_feature_dict(doc),category) for doc,category in training_documents]

In [55]:
training_data[0]

({'film': True,
  'movie': True,
  'one': True,
  'make': True,
  'like': True,
  'character': True,
  'get': True,
  'see': True,
  'time': True,
  'go': True,
  'well': True,
  'scene': True,
  'even': True,
  'good': False,
  'story': False,
  'take': True,
  'would': True,
  'much': False,
  'also': True,
  'bad': True,
  'come': True,
  'give': True,
  'way': True,
  'two': True,
  'look': False,
  'life': True,
  'first': True,
  'know': True,
  'seem': True,
  '--': False,
  'end': True,
  'work': True,
  'thing': False,
  'play': False,
  'year': False,
  'plot': True,
  'say': True,
  'really': False,
  'show': False,
  'people': True,
  'little': True,
  'man': False,
  'could': True,
  'love': False,
  'star': True,
  'never': False,
  'try': False,
  'director': False,
  'new': False,
  'performance': False,
  'action': False,
  'great': True,
  'best': True,
  'u': True,
  'actor': False,
  'many': False,
  'big': True,
  'watch': True,
  'want': True,
  'think': True,
  '

In [56]:
from nltk import NaiveBayesClassifier

In [57]:
classifier = NaiveBayesClassifier.train(training_data)

In [59]:
nltk.classify.accuracy(classifier,testing_data)

0.8913333333333333

In [60]:
classifier.show_most_informative_features(15)

Most Informative Features
             outstanding = True              pos : neg    =     18.3 : 1.0
               stupidity = True              neg : pos    =     16.9 : 1.0
                   anger = True              pos : neg    =      8.8 : 1.0
                   ideal = True              pos : neg    =      8.2 : 1.0
                  castle = True              pos : neg    =      7.8 : 1.0
               ludicrous = True              neg : pos    =      7.8 : 1.0
              schumacher = True              neg : pos    =      7.0 : 1.0
                  seagal = True              neg : pos    =      6.6 : 1.0
                   cindy = True              neg : pos    =      6.3 : 1.0
                  norton = True              pos : neg    =      6.2 : 1.0
                  tucker = True              pos : neg    =      6.2 : 1.0
             beautifully = True              pos : neg    =      5.9 : 1.0
              ridiculous = True              neg : pos    =      5.8 : 1.0

In [61]:
from sklearn.svm import SVC
from nltk.classify.scikitlearn import SklearnClassifier

In [63]:
svc = SVC()
classifier_svc = SklearnClassifier(svc)

In [64]:
classifier_svc.train(training_data)

<SklearnClassifier(SVC())>

In [65]:
nltk.classify.accuracy(classifier_svc,testing_data)

0.9946666666666667

In [67]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
rfc = RandomForestClassifier()
classifier_rfc = SklearnClassifier(rfc)


In [69]:
classifier_rfc.train(training_data)

<SklearnClassifier(RandomForestClassifier())>

In [70]:
nltk.classify.accuracy(classifier_rfc,testing_data)

1.0

In [71]:
from sklearn.feature_extraction.text import CountVectorizer


In [72]:
train_set = {"the sky sky is blue", "the sun is bright"}
count_vec = CountVectorizer(max_features=3)
a = count_vec.fit_transform(train_set)
a

<2x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [73]:
a.todense()

matrix([[1, 0, 1],
        [1, 2, 1]], dtype=int64)

In [75]:
count_vec.get_feature_names_out()

array(['is', 'sky', 'the'], dtype=object)

In [76]:
categories = [category for document, category in documents]

In [78]:
text_documents = [" ".join(document) for document, category in documents]

In [80]:
text_documents[0]

'warn follow review contains spoiler cast gary sinise cheadle connie nielsen jerry connell kim delaney tim robbins elise neal jill teed jody thompson bill timoney write jim thomas john thomas graham yost direct brian depalma run time 115 minute first big event movie 2000 turn anything gary sinise star astronaut remove mar mission astronaut wife maggie kim delaney becomes ill pass away cheadle give mission along russian couple young hotshot strange whirlwind shot top mar mountain range attack crew mission sinise robbins convince superior let neilsen connell perform rescue mission whatever crew might remain discover surface planet dramatically change life forever although one watch film come away profoundly affected ever saw film aware promotional campaign dr pepper every time would see bottle soft drink mission mar logo emblazon upon little know plot would take back seat product placement drink several product dr pepper save day one point dream sequence flashback feature jerry connell s

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
x_train, x_test, y_train, y_test = train_test_split(text_documents,categories,random_state=42)

In [100]:
count_vec = CountVectorizer(max_features=2000,ngram_range=(1,2))

In [101]:
a = count_vec.fit_transform(x_train)
a.todense()

matrix([[0, 0, 0, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 2, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [102]:
count_vec.get_feature_names_out()

array(['000', '10', '100', ..., 'york', 'young', 'zero'], dtype=object)

In [103]:
x_train_features = a

In [104]:
x_test_features = count_vec.transform(x_test)

In [105]:
x_test_features 

<500x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 87495 stored elements in Compressed Sparse Row format>

In [106]:
svc = SVC()
svc.fit(x_train_features,y_train)

SVC()

In [107]:
svc.score(x_test_features,y_test)

0.832

In [108]:
y_pred = svc.predict(x_test_features)

In [109]:
from sklearn.metrics import confusion_matrix

In [110]:
from sklearn.metrics import classification_report

In [111]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         neg       0.80      0.85      0.83       235
         pos       0.86      0.82      0.84       265

    accuracy                           0.83       500
   macro avg       0.83      0.83      0.83       500
weighted avg       0.83      0.83      0.83       500



In [112]:
print(confusion_matrix(y_test,y_pred))

[[200  35]
 [ 49 216]]
